"""Fail-closed LF-024 evidence admission and semantic label resolution."""

from leanfaith.labeling.aggregation import (
    EVIDENCE_ADMISSION_PREFIX,
    EVIDENCE_DERIVATION_PREFIX,
    EvidenceAdmissionRecord,
    EvidenceAggregationError,
    EvidenceDerivationRecord,
    EvidenceFactConflictError,
    build_evidence_admission_record,
    derive_admitted_evidence,
    verify_evidence_derivation,
)
from leanfaith.labeling.conflicts import (
    RESOLUTION_CONFLICT_PREFIX,
    RESOLUTION_OVERRIDE_PREFIX,
    ResolutionConflictReason,
    ResolutionConflictRecord,
    ResolutionOverrideReason,
    ResolutionOverrideRecord,
    build_resolution_conflict_record,
    build_resolution_override_record,
)
from leanfaith.labeling.quality import (
    ActiveLabelResolutionPolicy,
    AuthorityArtifactBinding,
    AuthorityArtifactKind,
    CandidateCommitment,
    LabelResolutionPolicyError,
    ResolutionCandidate,
    ResolutionSource,
    load_active_label_resolution_policy,
    make_authority_artifact_binding,
    make_authority_artifact_binding_id,
    make_resolution_candidate,
    make_resolution_candidate_id,
)
from leanfaith.labeling.resolution import (
    RESOLUTION_AUDIT_PREFIX,
    ResolutionArtifacts,
    ResolutionAuditRecord,
    ResolutionInputError,
    resolve_target,
    verify_resolution_artifacts,
)

__all__ = [
    "EVIDENCE_ADMISSION_PREFIX",
    "EVIDENCE_DERIVATION_PREFIX",
    "RESOLUTION_AUDIT_PREFIX",
    "RESOLUTION_CONFLICT_PREFIX",
    "RESOLUTION_OVERRIDE_PREFIX",
    "ActiveLabelResolutionPolicy",
    "AuthorityArtifactBinding",
    "AuthorityArtifactKind",
    "CandidateCommitment",
    "EvidenceAdmissionRecord",
    "EvidenceAggregationError",
    "EvidenceDerivationRecord",
    "EvidenceFactConflictError",
    "LabelResolutionPolicyError",
    "ResolutionArtifacts",
    "ResolutionAuditRecord",
    "ResolutionCandidate",
    "ResolutionConflictReason",
    "ResolutionConflictRecord",
    "ResolutionInputError",
    "ResolutionOverrideReason",
    "ResolutionOverrideRecord",
    "ResolutionSource",
    "build_evidence_admission_record",
    "build_resolution_conflict_record",
    "build_resolution_override_record",
    "derive_admitted_evidence",
    "load_active_label_resolution_policy",
    "make_authority_artifact_binding",
    "make_authority_artifact_binding_id",
    "make_resolution_candidate",
    "make_resolution_candidate_id",
    "resolve_target",
    "verify_evidence_derivation",
    "verify_resolution_artifacts",
]
